CREATE DATABASE IF NOT EXISTS APK_Uni;
USE APK_Uni;

CREATE TABLE IF NOT EXISTS user (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    username TEXT UNIQUE NOT NULL,
    secret_key TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS students (
    StudentID INTEGER PRIMARY KEY AUTO_INCREMENT,
    `Name` TEXT NOT NULL,
    Surname TEXT NOT NULL,
    NIN TEXT UNIQUE NOT NULL,
    Birth TEXT NOT NULL,
    `Credential` TEXT NOT NULL
);

CREATE TABLE integrity (
    NIN TEXT UNIQUE NOT NULL,
    `checksum` TEXT NOT NULL
);
